give @p simple_vehicles:steer_ae86
give @p simple_vehicles:steer_ambulance
give @p simple_vehicles:steer_auv_car
give @p simple_vehicles:steer_bike
give @p simple_vehicles:steer_bus
give @p simple_vehicles:steer_bus_v2
give @p simple_vehicles:steer_car
give @p simple_vehicles:steer_car_4x4
give @p simple_vehicles:steer_corolla
give @p simple_vehicles:steer_ev_4
give @p simple_vehicles:steer_fire_truck
give @p simple_vehicles:steer_grummanllv
give @p simple_vehicles:steer_helicopter
give @p simple_vehicles:steer_jeep_ph
give @p simple_vehicles:steer_jetmax
give @p simple_vehicles:steer_land_cruiser
give @p simple_vehicles:steer_limmo
give @p simple_vehicles:steer_lowrider_car
give @p simple_vehicles:steer_mini_bus
give @p simple_vehicles:steer_modern_jeep_ph
give @p simple_vehicles:steer_motor
give @p simple_vehicles:steer_motorcycle
give @p simple_vehicles:steer_mustang
give @p simple_vehicles:steer_ob_van
give @p simple_vehicles:steer_pajero