give @p simple_vehicles:tire_ae86
give @p simple_vehicles:tire_ambulance
give @p simple_vehicles:tire_armored_truck
give @p simple_vehicles:tire_auv_car
give @p simple_vehicles:tire_bike
give @p simple_vehicles:tire_bus
give @p simple_vehicles:tire_bus_v2
give @p simple_vehicles:tire_car
give @p simple_vehicles:tire_car_4x4
give @p simple_vehicles:tire_corolla
give @p simple_vehicles:tire_ev_4
give @p simple_vehicles:tire_fire_truck
give @p simple_vehicles:tire_grummanllv
give @p simple_vehicles:tire_hoverboard
give @p simple_vehicles:tire_jeep_ph
give @p simple_vehicles:tire_land_cruiser
give @p simple_vehicles:tire_large_tractor
give @p simple_vehicles:tire_limmo
give @p simple_vehicles:tire_lowrider_car
give @p simple_vehicles:tire_mini_bus
give @p simple_vehicles:tire_modern_jeep_ph
give @p simple_vehicles:tire_motor
give @p simple_vehicles:tire_motorcycle
give @p simple_vehicles:tire_mustang
give @p simple_vehicles:tire_ob_van